"""empty message

Revision ID: 339b529b797f
Revises: 3b8ea62c155d
Create Date: 2021-05-07 14:36:07.497189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339b529b797f'
down_revision = '3b8ea62c155d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_creator', sa.Integer(), nullable=False),
    sa.Column('max_bikers', sa.Integer(), nullable=True),
    sa.Column('area', sa.String(length=256), nullable=False),
    sa.Column('trail', sa.String(length=256), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('min_skill', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_creator'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting')
    # ### end Alembic commands ###
