"""empty message

Revision ID: 4534f710fe5c
Revises: 8fbfe8104980
Create Date: 2021-05-08 15:41:59.900772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4534f710fe5c'
down_revision = '8fbfe8104980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('meet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meet_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participants')
    # ### end Alembic commands ###
